Repository Unrated-Limited-Unlimited/ua-backend, pull requests merged in 2024-04, with the labels that each got.

#26 Rating Attributes
  src/main/kotlin/com/ulu/Application.kt
  src/main/kotlin/com/ulu/factories/GraphQLFactory.kt
  src/main/kotlin/com/ulu/fetchers/AttributeCategoryFetcher.kt
  src/main/kotlin/com/ulu/fetchers/LabelFetcher.kt
  src/main/kotlin/com/ulu/fetchers/RatingFetcher.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/models/Attribute.kt
  src/main/kotlin/com/ulu/models/AttributeCategory.kt
  src/main/kotlin/com/ulu/models/Label.kt
  src/main/kotlin/com/ulu/models/Rating.kt
  src/main/kotlin/com/ulu/models/UserData.kt
  src/main/kotlin/com/ulu/models/Whiskey.kt
  src/main/kotlin/com/ulu/repositories/AttributeCategoryRepository.kt
  src/main/kotlin/com/ulu/repositories/AttributeRepository.kt
  src/main/kotlin/com/ulu/services/DatabaseService.kt
  src/main/kotlin/com/ulu/sorters/SortByBestRating.kt
  src/main/resources/schema.graphqls
  src/test/kotlin/com/ulu/JpaTest.kt
  src/test/kotlin/com/ulu/graphql/AttributeCategoryTest.kt
Labels: help wanted

#28 Explicitly defined CORS paths
  src/main/kotlin/com/ulu/fetchers/RatingFetcher.kt
  src/main/kotlin/com/ulu/services/AccountCreationService.kt
  src/main/resources/application.yml
  src/test/kotlin/com/ulu/graphql/AttributeCategoryTest.kt
  src/test/kotlin/com/ulu/graphql/RatingTest.kt
Labels: bug

#36 Whiskey filters
  src/main/kotlin/com/ulu/Application.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/resources/schema.graphqls
  src/test/kotlin/com/ulu/graphql/WhiskeyTest.kt
Labels: enhancement

#38 Image uploading to file storage through backend.
  src/main/kotlin/com/ulu/controllers/ImageController.kt
  src/main/kotlin/com/ulu/fetchers/RatingFetcher.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/models/Whiskey.kt
  src/main/kotlin/com/ulu/repositories/RatingRepository.kt
  src/main/kotlin/com/ulu/services/UploadService.kt
  src/main/resources/schema.graphqls
  src/test/kotlin/com/ulu/graphql/RatingTest.kt
Labels: enhancement

#40 OpenAPI docs and rating serialization for thumb stats when quering getWhiskey(id)
  README.md
  images/jpaUnrated.png
  openapi.properties
  src/main/kotlin/com/ulu/Application.kt
  src/main/kotlin/com/ulu/controllers/AuthController.kt
  src/main/kotlin/com/ulu/controllers/DocsController.kt
  src/main/kotlin/com/ulu/controllers/ImageController.kt
  src/main/kotlin/com/ulu/dto/LoginRequest.kt
  src/main/kotlin/com/ulu/dto/RegisterRequest.kt
  src/main/kotlin/com/ulu/factories/GraphQLFactory.kt
  src/main/kotlin/com/ulu/fetchers/AttributeCategoryFetcher.kt
  src/main/kotlin/com/ulu/fetchers/RatingFetcher.kt
  src/main/kotlin/com/ulu/fetchers/UserDataFetcher.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/models/AttributeCategory.kt
  src/main/kotlin/com/ulu/models/Rating.kt
  src/main/kotlin/com/ulu/models/Whiskey.kt
  src/main/kotlin/com/ulu/security/LoginProvider.kt
  src/main/kotlin/com/ulu/services/AccountCreationService.kt
  src/main/kotlin/com/ulu/services/AccountService.kt
  src/main/resources/application.yml
  src/main/resources/schema.graphqls
  src/test/kotlin/com/ulu/JpaTest.kt
  src/test/kotlin/com/ulu/OpenApiGeneratedTest.kt
  src/test/kotlin/com/ulu/SortersTest.kt
  src/test/kotlin/com/ulu/UploadServiceTest.kt
  src/test/kotlin/com/ulu/graphql/AttributeCategoryTest.kt
  src/test/kotlin/com/ulu/graphql/RatingTest.kt
  src/test/kotlin/com/ulu/graphql/ThumbTest.kt
  src/test/kotlin/com/ulu/graphql/UserDataTest.kt
  src/test/kotlin/com/ulu/graphql/WhiskeyTest.kt
  src/test/kotlin/com/ulu/security/AuthControllerTest.kt
  src/test/kotlin/com/ulu/security/JwtAuthenticationTest.kt
Labels: documentation, enhancement, refactor

#41 Change getUser to either use id or username.
  src/main/kotlin/com/ulu/fetchers/UserDataFetcher.kt
  src/main/resources/schema.graphqls
Labels: enhancement

#43 Dev recommendations
  build.gradle.kts
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/sorters/ResponseData.kt
  src/main/kotlin/com/ulu/sorters/SortByRecommendations.kt
  src/test/kotlin/com/ulu/RecommendationTest.kt
Labels: enhancement

#48 Bug fixes: Paging with filtering bug + getWhiskey(id) query bug + overshadowed logout endpoint
  src/main/kotlin/com/ulu/controllers/AuthController.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/repositories/RatingRepository.kt
  src/main/kotlin/com/ulu/repositories/WhiskeyRepository.kt
  src/main/kotlin/com/ulu/security/JwtPersistenceProvider.kt
  src/main/kotlin/com/ulu/services/RequestValidatorService.kt
  src/main/resources/application.yml
Labels: bug

#49 Push to main
  src/main/kotlin/com/ulu/controllers/AuthController.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/repositories/RatingRepository.kt
  src/main/kotlin/com/ulu/repositories/WhiskeyRepository.kt
  src/main/kotlin/com/ulu/security/JwtPersistenceProvider.kt
  src/main/kotlin/com/ulu/services/RequestValidatorService.kt
  src/main/resources/application.yml
Labels: bug

#51 Fix editRating
  src/main/kotlin/com/ulu/fetchers/RatingFetcher.kt
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
Labels: bug

#54 Added some new fancy sorters
  src/main/kotlin/com/ulu/fetchers/WhiskeyFetcher.kt
  src/main/kotlin/com/ulu/sorters/SortByHighestRating.kt
  src/main/kotlin/com/ulu/sorters/SortByPrice.kt
  src/main/kotlin/com/ulu/sorters/SortByValue.kt
  src/main/resources/schema.graphqls
  src/test/kotlin/com/ulu/SortersTest.kt
Labels: enhancement
